export enum Club {
    DRIVER = 1,
    THREE_WOOD = 2,
    FIVE_WOOD = 3,
    SEVEN_WOOD = 4,
    NINE_WOOD = 5,
    TWO_HYBRID = 6,
    THREE_HYBRID = 7,
    FOUR_HYBRID = 8,
    FIVE_HYBRID = 9,
    TWO_IRON = 10,
    THREE_IRON = 11,
    FOUR_IRON = 12,
    FIVE_IRON = 13,
    SIX_IRON = 14,
    SEVEN_IRON = 15,
    EIGHT_IRON = 16,
    NINE_IRON = 17,
    PW = 18,
    GW = 19,
    SW = 20,
    LW = 21,
    AW = 22
};